### ISSUE TITLE
seed_r7_samples_test failure

### ISSUE THREAD

**Issue by hi-kondo** [seed-solutions/seed_r7_ros_pkg#60]
I'm checking ros-test for seed_r7_samples.
However, runtime error occurs at "DownLifter", so fail to unit-test.

```
RuntimeError: Unable to connect to move_group action server 'pickup' within allotted time (5s)
```
It seems to occur loading movegroupinterface "torso" .

The below is all log when testing seed_r7_samples.
```
==> Processing catkin package: 'seed_r7_samples'
==> Building with env: '/tmp/ws/devel_isolated/seed_r7_typef_moveit_config/env.sh'
==> cmake /tmp/ws/src/seed_r7_ros_pkg/seed_r7_samples -DCATKIN_DEVEL_PREFIX=/tmp/ws/devel_isolated/seed_r7_samples -DCMAKE_INSTALL_PREFIX=/tmp/ws/install_isolated -DBUILD_TESTING=1 -DCATKIN_ENABLE_TESTING=1 -DCATKIN_SKIP_TESTING=0 -DCATKIN_TEST_RESULTS_DIR=/tmp/ws/test_results -G Unix Makefiles in '/tmp/ws/build_isolated/seed_r7_samples'
-- Using CATKIN_DEVEL_PREFIX: /tmp/ws/devel_isolated/seed_r7_samples
-- Using CMAKE_PREFIX_PATH: /tmp/ws/devel_isolated/seed_r7_ros_pkg;/tmp/ws/devel_isolated/seed_r7_samples;/tmp/ws/devel_isolated/seed_r7_typef_moveit_config;/tmp/ws/devel_isolated/seed_r7_robot_interface;/tmp/ws/devel_isolated/seed_r7_ros_controller;/tmp/ws/devel_isolated/seed_r7_navigation;/tmp/ws/devel_isolated/seed_r7_moveit_config;/tmp/ws/devel_isolated/seed_r7_description;/tmp/ws/devel_isolated/seed_r7_bringup;/opt/ros/kinetic
-- This workspace overlays: /tmp/ws/devel_isolated/seed_r7_ros_pkg;/tmp/ws/devel_isolated/seed_r7_samples;/tmp/ws/devel_isolated/seed_r7_typef_moveit_config;/tmp/ws/devel_isolated/seed_r7_robot_interface;/tmp/ws/devel_isolated/seed_r7_ros_controller;/tmp/ws/devel_isolated/seed_r7_navigation;/tmp/ws/devel_isolated/seed_r7_moveit_config;/tmp/ws/devel_isolated/seed_r7_description;/tmp/ws/devel_isolated/seed_r7_bringup;/opt/ros/kinetic
-- Found PythonInterp: /usr/bin/python2 (found suitable version "2.7.12", minimum required is "2") 
-- Using PYTHON_EXECUTABLE: /usr/bin/python2
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: 1

-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /tmp/ws/test_results
-- Found gmock sources under '/usr/src/gmock': gmock will be built
-- Found PythonInterp: /usr/bin/python2 (found version "2.7.12") 
-- Found gtest sources under '/usr/src/gmock': gtests will be built
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.7.18
-- BUILD_SHARED_LIBS is on
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/ws/build_isolated/seed_r7_samples
==> make run_tests in '/tmp/ws/build_isolated/seed_r7_samples'

Scanning dependencies of target clean_test_results_seed_r7_samples
Removing test result files from '/tmp/ws/test_results/seed_r7_samples'
Built target clean_test_results_seed_r7_samples
Built target tests
Scanning dependencies of target _run_tests_seed_r7_samples_rostest_test_demo.test
-- run_tests.py: execute commands
  /opt/ros/kinetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/tmp/ws/src/seed_r7_ros_pkg/seed_r7_samples --package=seed_r7_samples --results-filename test_demo.xml --results-base-dir "/tmp/ws/test_results" /tmp/ws/src/seed_r7_ros_pkg/seed_r7_samples/test/demo.test 
... logging to /home/buildfarm/.ros/log/rostest-04f82467e5a9-2540.log

[ROSUNIT] Outputting test results to /tmp/ws/test_results/seed_r7_samples/rostest-test_demo.xml
[ERROR] [1575256045.675841735]: /dev/aero_upper is not connected
[ERROR] [1575256045.682386383]: /dev/aero_lower is not connected
the rosdep view is empty: call 'sudo rosdep init' and 'rosdep update'
the rosdep view is empty: call 'sudo rosdep init' and 'rosdep update'
Failed to import pyassimp, see https://github.com/ros-planning/moveit/issues/86 for more info
[INFO] [1575256053.196589]: Waiting for the move_base action server to come up
[INFO] [1575256053.668026]: The server comes up
[INFO] [1575256053.669107]: waiting service
[ INFO] [1575256053.769165931]: Loading robot model 'SEED-Noid-Mover-typeF'...
[ INFO] [1575256055.826075174]: Loading robot model 'SEED-Noid-Mover-typeF'...
[ INFO] [1575256056.413982768]: Loading robot model 'SEED-Noid-Mover-typeF'...
[ INFO] [157525605.058097651]: Loading robot model 'SEED-Noid-Mover-typeF'...
[ INFO] [1575256058.029054878]: Loading robot model 'SEED-Noid-Mover-typeF'...
[ INFO] [1575256058.924486110]: Loading robot model 'SEED-Noid-Mover-typeF'...
[ INFO] [1575256059.774821235]: Loading robot model 'SEED-Noid-Mover-typeF'...
[ INFO] [1575256060.400220168]: Loading robot model 'SEED-Noid-Mover-typeF'...
[ INFO] [1575256060.973709329]: Loading robot model 'SEED-Noid-Mover-typeF'...
[ INFO] [1575256061.577633795]: Loading robot model 'SEED-Noid-Mover-typeF'...
[ INFO] [1575256062.218197626]: Loading robot model 'SEED-Noid-Mover-typeF'...
[ INFO] [1575256046.926725264]: Loading robot model 'SEED-Noid-Mover-typeF'...
[ INFO] [1575256049.119248242]: Loading robot model 'SEED-Noid-Mover-typeF'...
[ INFO] [1575256049.666908493]: Loading robot model 'SEED-Noid-Mover-typeF'...
[ INFO] [1575256050.273383228]: Loading robot model 'SEED-Noid-Mover-typeF'...
[ INFO] [1575256050.893656381]: Loading robot model 'SEED-Noid-Mover-typeF'...
[ INFO] [1575256051.510285514]: Loading robot model 'SEED-Noid-Mover-typeF'...
[ INFO] [1575256052.062627907]: Loading robot model 'SEED-Noid-Mover-typeF'...
[ INFO] [1575256052.653401910]: Loading robot model 'SEED-Noid-Mover-typeF'...
[ INFO] [1575256053.178506290]: Loading robot model 'SEED-Noid-Mover-typeF'...
[ INFO] [1575256053.910035845]: Loading robot model 'SEED-Noid-Mover-typeF'...
[ INFO] [1575256054.815236572]: Loading robot model 'SEED-Noid-Mover-typeF'...
[ INFO] [1575256057.035715006]: Publishing maintained planning scene on 'monitored_planning_scene'

[ INFO] [1575256057.075760541]: MoveGroup debug mode is OFF

Starting context monitors...

[ INFO] [1575256057.075813893]: Starting scene monitor

[ INFO] [1575256057.114403955]: Listening to '/planning_scene'
[ INFO] [1575256057.114463660]: Starting world geometry monitor
[ INFO] [1575256057.144097848]: Listening to '/collision_object' using message notifier with target frame '/odom '
[ INFO] [1575256057.178260808]: Listening to '/planning_scene_world' for planning scene world geometry
[ INFO] [1575256059.432143863]: Listening to '/head_mount_kinect/depth_registered/points' using message filter with target frame '/odom '
[ INFO] [1575256059.446752530]: Listening to '/attached_collision_object' for attached collision objects

Context monitors started.

[ INFO] [1575256059.528731578]: Initializing OMPL interface using ROS parameters
[ INFO] [1575256062.185891794]: Using planning interface 'OMPL'
[ INFO] [1575256062.190785125]: Param 'default_workspace_bounds' was not set. Using default value: 10
[ INFO] [1575256062.207052756]: Param 'start_state_max_bounds_error' was set to 0.1
[ INFO] [1575256062.211897165]: Param 'start_state_max_dt' was not set. Using default value: 0.5
[ INFO] [1575256062.212829516]: Param 'start_state_max_dt' was not set. Using default value: 0.5
[ INFO] [1575256062.213654939]: Param 'jiggle_fraction' was set to 0.05
[ INFO] [1575256062.214434578]: Param 'max_sampling_attempts' was not set. Using default value: 100
[ INFO] [1575256062.214518695]: Using planning request adapter 'Add Time Parameterization'
[ INFO] [1575256062.214537057]: Using planning request adapter 'Fix Workspace Bounds'
[ INFO] [1575256062.214548214]: Using planning request adapter 'Fix Start State Bounds'
[ INFO] [1575256062.214560420]: Using planning request adapter 'Fix Start State In Collision'
[ INFO] [1575256062.214572640]: Using planning request adapter 'Fix Start State Path Constraints'
[ INFO] [1575256062.619588595]: Added FollowJointTrajectory controller for rarm_controller
[ INFO] [1575256063.027826443]: Added FollowJointTrajectory controller for larm_controller
[ INFO] [1575256063.331301012]: Added FollowJointTrajectory controller for waist_controller
[ INFO] [1575256063.533582639]: Added FollowJointTrajectory controller for lifter_controller
[ INFO] [1575256063.735933144]: Added FollowJointTrajectory controller for head_controller
[ INFO] [1575256063.736117437]: Returned 5 controllers in list
[ INFO] [1575256063.782319105]: Trajectory execution is managing controllers

Loading 'move_group/ApplyPlanningSceneService'...
Loading 'move_group/ClearOctomapService'...
Loading 'move_group/MoveGroupCartesianPathService'...
Loading 'move_group/MoveGroupExecuteTrajectoryAction'...
Loading 'move_group/MoveGroupGetPlanningSceneService'...
Loading 'move_group/MoveGroupKinematicsService'...
Loading 'move_group/MoveGroupMoveAction'...
Loading 'move_group/MoveGroupPickPlaceAction'...
Loading 'move_group/MoveGroupPlanService'...
Loading 'move_group/MoveGroupQueryPlannersService'...
Loading 'move_group/MoveGroupStateValidationService'...

[ INFO] [1575256064.025593040]: 

********************************************************

* MoveGroup using: 

*     - ApplyPlanningSceneService
*     - ClearOctomapService
*     - CartesianPathService
*     - ExecuteTrajectoryAction
*     - GetPlanningSceneService
*     - KinematicsService
*     - MoveAction
*     - PickPlaceAction
*     - MotionPlanService
*     - QueryPlannersService
*     - StateValidationService

********************************************************

[ INFO] [1575256064.025663544]: MoveGroup context using planning plugin ompl_interface/OMPLPlanner
[ INFO] [1575256064.025725585]: MoveGroup context initialization complete

You can start planning now!

[ INFO] [1575256065.046132452]: Ready to take commands for planning group rarm_with_torso.
[INFO] [1575256065.088859]: State machine starting in initial state 'GO TO SHELF' with userdata: 

	[]

[INFO] [1575256065.092503]: State machine starting in initial state 'DOWN LIFTER' with userdata: 
	[]

Move Lifter at (0,0.6) in scale velocity 1.0

[WARN] [1575256066.869409]: Controller Spawner error while taking down controllers: unable to connect to service: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[ INFO] [1575256045.672273341]: upper_port: /dev/aero_upper
[ INFO] [1575256045.672354184]: lower_port: /dev/aero_lower
[ INFO] [1575256045.672370977]: cycle: 20.000000 [ms], overlap_scale 2.000000
[ INFO] [1575256045.684893883]: start to make stroke convert table
[ INFO] [1575256045.685741666]: finish to make stroke convert table
[ INFO] [1575256045.701836786]: Upper Firmware Ver. is [  ]
[ INFO] [1575256045.701872638]: Lower Firmware Ver. is [  ]
[ INFO] [1575256045.747631870]: hand_control_server start
[ INFO] [1575256045.775266623]: sendnum : 12, script : 4
[ INFO] [1575256045.775305818]: sendnum : 27, script : 4
[ INFO] [1575256045.775319638]: Initialized Handcontroller
[ INFO] [1575256045.853041216]: ControllerManager start with 50.000000 Hz
[ INFO] [1575256047.903144147]: max: 21.742176 [ms], ave: 20.091542 [ms]
[ INFO] [1575256049.938119856]: max: 23.171213 [ms], ave: 20.132551 [ms]
[ INFO] [1575256051.965092256]: max: 20.163296 [ms], ave: 20.091729 [ms]
[ INFO] [1575256053.994786624]: max: 22.045622 [ms], ave: 20.100715 [ms]
[ INFO] [1575256056.028201185]: max: 22.368767 [ms], ave: 20.119782 [ms]
[ INFO] [1575256058.056328314]: max: 20.824920 [ms], ave: 20.097352 [ms]
[ INFO] [1575256060.086062763]: max: 22.582760 [ms], ave: 20.104238 [ms]
[ INFO] [1575256062.115345750]: max: 21.748940 [ms], ave: 20.099204 [ms]
[ INFO] [1575256064.145462824]: max: 22.405247 [ms], ave: 20.096937 [ms]

[ INFO] [1575256049.032171507]: Using plugin "static"
[ INFO] [1575256049.059432996]: Requesting the map...
[ INFO] [1575256049.277825870]: Resizing costmap to 800 X 800 at 0.020000 m/pix
[ INFO] [1575256049.377145140]: Received a 800 X 800 map at 0.020000 m/pix
[ INFO] [1575256049.377184261]: Subscribing to updates
[ INFO] [1575256049.442632492]: Using plugin "inflation"
[ INFO] [1575256049.925096564]: Using plugin "obstacles_laser"
[ INFO] [1575256049.944797727]:     Subscribed to Topics: laser
[ INFO] [1575256050.148897188]: Using plugin "inflation"
[ INFO] [1575256050.508040691]: Created local_planner teb_local_planner/TebLocalPlannerROS
[ INFO] [1575256051.115797543]: Footprint model 'line' (line_start: [-0.1,0]m, line_end: [0.1,0]m) loaded for trajectory optimization.
[ INFO] [1575256051.116465603]: Parallel planning in distinctive topologies disabled.
[ INFO] [1575256051.430753868]: Costmap conversion plugin costmap_converter::CostmapToLinesDBSRANSAC loaded.
[ INFO] [1575256053.262565975]: Recovery behavior will clear layer obstacles
[ INFO] [1575256053.325750854]: Recovery behavior will clear layer obstacles
[ INFO] [1575256053.758141331]: odom received!
[INFO] [1575256070.099800]: The robot was terminated
[ERROR] [1575256070.726613]: InvalidUserCodeError: Could not execute state 'DOWN LIFTER' of type '<__main__.MOVE_LIFTER object at 0x7fa54f8dc190>': Traceback (most recent call last):

  File "/opt/ros/kinetic/lib/python2.7/dist-packages/smach/state_machine.py", line 247, in _update_once

    self._remappings[self._current_label]))

  File "/tmp/ws/src/seed_r7_ros_pkg/seed_r7_samples/scripts/demo.py", line 294, in execute

    if(mc.set_lifter_position(self.x,self.z,self.vel) == 'succeeded'):return 'succeeded'

  File "/tmp/ws/src/seed_r7_ros_pkg/seed_r7_samples/scripts/demo.py", line 151, in set_lifter_position

    self.group = moveit_commander.MoveGroupCommander("torso")

  File "/opt/ros/kinetic/lib/python2.7/dist-packages/moveit_commander/move_group.py", line 52, in __init__

    self._g = _moveit_move_group_interface.MoveGroupInterface(name, robot_description, ns)

RuntimeError: Unable to connect to move_group action server 'pickup' within allotted time (5s)

[ERROR] [1575256070.727148]: State 'GO TO SHELF' failed to execute.
Traceback (most recent call last):
  File "/tmp/ws/src/seed_r7_ros_pkg/seed_r7_samples/scripts/demo.py", line 431, in <module>
    scenario_play.execute()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/smach/state_machine.py", line 359, in execute

    container_outcome = self._update_once()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/smach/state_machine.py", line 250, in _update_once
    raise ex
smach.exceptions.InvalidUserCodeError: Could not execute state 'DOWN LIFTER' of type '<__main__.MOVE_LIFTER object at 0x7fa54f8dc190>': Traceback (most recent call last):

  File "/opt/ros/kinetic/lib/python2.7/dist-packages/smach/state_machine.py", line 247, in _update_once

    self._remappings[self._current_label]))

  File "/tmp/ws/src/seed_r7_ros_pkg/seed_r7_samples/scripts/demo.py", line 294, in execute

    if(mc.set_lifter_position(self.x,self.z,self.vel) == 'succeeded'):return 'succeeded'

  File "/tmp/ws/src/seed_r7_ros_pkg/seed_r7_samples/scripts/demo.py", line 151, in set_lifter_position

    self.group = moveit_commander.MoveGroupCommander("torso")

  File "/opt/ros/kinetic/lib/python2.7/dist-packages/moveit_commander/move_group.py", line 52, in __init__

    self._g = _moveit_move_group_interface.MoveGroupInterface(name, robot_description, ns)

RuntimeError: Unable to connect to move_group action server 'pickup' within allotted time (5s)
[Testcase: teststate_publishment] ... ok
[ROSTEST]-----------------------------------------------------------------------

[seed_r7_samples.rosunit-state_publishment/test_publish][FAILURE]---------------
Topic [/server_name/smach/container_status] is not published
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run

    testMethod()

  File "/opt/ros/kinetic/share/rostest/nodes/publishtest", line 149, in test_publish

    'Topic [%s] is not published' % (checker.topic_name))

  File "/usr/lib/python2.7/unittest/case.py", line 422, in assertTrue

    raise self.failureException(msg)
--------------------------------------------------------------------------------
SUMMARY
 * RESULT: FAIL
 * TESTS: 1
 * ERRORS: 0
 * FAILURES: 1
```

**Comment by hi-kondo** [comment]
[This is CI test result.](https://travis-ci.com/hi-kondo/seed_r7_ros_pkg/jobs/262003622#L17205)

**Comment by hi-kondo** [comment]
Runtimeerror resolved.
But a new error occured.

```
==> Processing catkin package: 'seed_r7_samples'
==> Building with env: '/tmp/ws/devel_isolated/seed_r7_typef_moveit_config/env.sh'
==> cmake /tmp/ws/src/seed_r7_ros_pkg/seed_r7_samples -DCATKIN_DEVEL_PREFIX=/tmp/ws/devel_isolated/seed_r7_samples -DCMAKE_INSTALL_PREFIX=/tmp/ws/install_isolated -DBUILD_TESTING=1 -DCATKIN_ENABLE_TESTING=1 -DCATKIN_SKIP_TESTING=0 -DCATKIN_TEST_RESULTS_DIR=/tmp/ws/test_results -G Unix Makefiles in '/tmp/ws/build_isolated/seed_r7_samples'
-- Using CATKIN_DEVEL_PREFIX: /tmp/ws/devel_isolated/seed_r7_samples
-- Using CMAKE_PREFIX_PATH: /tmp/ws/devel_isolated/seed_r7_ros_pkg;/tmp/ws/devel_isolated/seed_r7_samples;/tmp/ws/devel_isolated/seed_r7_typef_moveit_config;/tmp/ws/devel_isolated/seed_r7_robot_interface;/tmp/ws/devel_isolated/seed_r7_ros_controller;/tmp/ws/devel_isolated/seed_r7_navigation;/tmp/ws/devel_isolated/seed_r7_moveit_config;/tmp/ws/devel_isolated/seed_r7_description;/tmp/ws/devel_isolated/seed_r7_bringup;/opt/ros/kinetic
-- This workspace overlays: /tmp/ws/devel_isolated/seed_r7_ros_pkg;/tmp/ws/devel_isolated/seed_r7_samples;/tmp/ws/devel_isolated/seed_r7_typef_moveit_config;/tmp/ws/devel_isolated/seed_r7_robot_interface;/tmp/ws/devel_isolated/seed_r7_ros_controller;/tmp/ws/devel_isolated/seed_r7_navigation;/tmp/ws/devel_isolated/seed_r7_moveit_config;/tmp/ws/devel_isolated/seed_r7_description;/tmp/ws/devel_isolated/seed_r7_bringup;/opt/ros/kinetic
-- Found PythonInterp: /usr/bin/python2 (found suitable version "2.7.12", minimum required is "2") 
-- Using PYTHON_EXECUTABLE: /usr/bin/python2
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: 1
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /tmp/ws/test_results
-- Found gmock sources under '/usr/src/gmock': gmock will be built
-- Found PythonInterp: /usr/bin/python2 (found version "2.7.12") 
-- Found gtest sources under '/usr/src/gmock': gtests will be built
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.7.18
-- BUILD_SHARED_LIBS is on
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/ws/build_isolated/seed_r7_samples
==> make run_tests in '/tmp/ws/build_isolated/seed_r7_samples'
Scanning dependencies of target clean_test_results_seed_r7_samples
Removing test result files from '/tmp/ws/test_results/seed_r7_samples'
Built target clean_test_results_seed_r7_samples
Built target tests
Scanning dependencies of target _run_tests_seed_r7_samples_rostest_test_demo.test
-- run_tests.py: execute commands
  /opt/ros/kinetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/tmp/ws/src/seed_r7_ros_pkg/seed_r7_samples --package=seed_r7_samples --results-filename test_demo.xml --results-base-dir "/tmp/ws/test_results" /tmp/ws/src/seed_r7_ros_pkg/seed_r7_samples/test/demo.test 
... logging to /home/buildfarm/.ros/log/rostest-3cc7d55f95a0-2539.log
[ROSUNIT] Outputting test results to /tmp/ws/test_results/seed_r7_samples/rostest-test_demo.xml
[ERROR] [1575266708.874977347]: /dev/aero_upper is not connected
[ERROR] [1575266708.880695084]: /dev/aero_lower is not connected
the rosdep view is empty: call 'sudo rosdep init' and 'rosdep update'
QXcbConnection: Could not connect to display 
Traceback (most recent call last):
  File "/opt/ros/kinetic/share/rostest/nodes/publishtest", line 58, in <module>
    import unittest
  File "/usr/lib/python2.7/unittest/__init__.py", line 58, in <module>
    from .result import TestResult
  File "/usr/lib/python2.7/unittest/result.py", line 9, in <module>
    from . import util
  File "/usr/lib/python2.7/unittest/util.py", line 2, in <module>
    from collections import namedtuple, OrderedDict
  File "/usr/lib/python2.7/collections.py", line 11, in <module>
    '''
KeyboardInterrupt
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/smach_viewer/smach_viewer.py", line 33, in <module>
    import rospy
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/__init__.py", line 47, in <module>
    from std_msgs.msg import Header
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/std_msgs/msg/__init__.py", line 22, in <module>
    from ._MultiArrayLayout import *
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/std_msgs/msg/_MultiArrayLayout.py", line 2, in <module>
    """autogenerated by genpy from std_msgs/MultiArrayLayout.msg. Do not edit."""
KeyboardInterrupt
Traceback (most recent call last):
  File "/tmp/ws/src/seed_r7_ros_pkg/seed_r7_samples/scripts/demo.py", line 5, in <module>
    import rospy
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/__init__.py", line 47, in <module>
    from std_msgs.msg import Header
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/std_msgs/msg/__init__.py", line 1, in <module>
    from ._Bool import *
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/std_msgs/msg/_Bool.py", line 5, in <module>
    import genpy
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genpy/__init__.py", line 34, in <module>
    from . message import Message, SerializationError, DeserializationError, MessageException, struct_I
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genpy/message.py", line 44, in <module>
    import yaml
  File "/usr/lib/python2.7/dist-packages/yaml/__init__.py", line 8, in <module>
    from loader import *
  File "/usr/lib/python2.7/dist-packages/yaml/loader.py", line 4, in <module>
    from reader import *
  File "/usr/lib/python2.7/dist-packages/yaml/reader.py", line 47, in <module>
    class Reader(object):
  File "/usr/lib/python2.7/dist-packages/yaml/reader.py", line 140, in Reader
    NON_PRINTABLE = re.compile(u'[^\x09\x0A\x0D\x20-\x7E\x85\xA0-\uD7FF\uE000-\uFFFD\U00010000-\U0010ffff]')
  File "/usr/lib/python2.7/re.py", line 194, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python2.7/re.py", line 249, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python2.7/sre_compile.py", line 576, in compile
    code = _code(p, flags)
  File "/usr/lib/python2.7/sre_compile.py", line 558, in _code
    _compile_info(code, p, flags)
  File "/usr/lib/python2.7/sre_compile.py", line 536, in _compile_info
    _compile_charset(charset, flags, code)
  File "/usr/lib/python2.7/sre_compile.py", line 232, in _compile_charset
    flags & SRE_FLAG_UNICODE):
  File "/usr/lib/python2.7/sre_compile.py", line 274, in _optimize_charset
    r = range(av[0], av[1]+1)
KeyboardInterrupt
[ INFO] [1575266709.794560545]: Loading robot model 'SEED-Noid-Mover-typeF'...
Starting context monitors...
Context monitors started.
Loading 'move_group/ApplyPlanningSceneService'...
Loading 'move_group/ClearOctomapService'...
Loading 'move_group/MoveGroupCartesianPathService'...
Loading 'move_group/MoveGroupExecuteTrajectoryAction'...
Loading 'move_group/MoveGroupGetPlanningSceneService'...
Loading 'move_group/MoveGroupKinematicsService'...
Loading 'move_group/MoveGroupMoveAction'...
Loading 'move_group/MoveGroupPickPlaceAction'...
Loading 'move_group/MoveGroupPlanService'...
Loading 'move_group/MoveGroupQueryPlannersService'...
Loading 'move_group/MoveGroupStateValidationService'...
You can start planning now!
[WARN] [1575266725.475214]: Controller Spawner error while taking down controllers: transport error completing service call: receive_once[/controller_manager/switch_controller]: unexpected error [Errno 4] Interrupted system call
Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/controller_manager/spawner", line 207, in <module>
    if __name__ == '__main__': main()
  File "/opt/ros/kinetic/lib/controller_manager/spawner", line 185, in main
    resp = load_controller(name)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 435, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 523, in call
    raise rospy.exceptions.ROSInterruptException("node shutdown interrupted service call")
rospy.exceptions.ROSInterruptException: node shutdown interrupted service call
[Testcase: teststate_publishtest] ... FAILURE!
FAILURE: test [state_publishtest] did not generate test results
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rostest/runner.py", line 164, in fn
    self.assert_(os.path.isfile(test_file), "test [%s] did not generate test results"%test_name)
  File "/usr/lib/python2.7/unittest/case.py", line 422, in assertTrue
    raise self.failureException(msg)
--------------------------------------------------------------------------------
[ROSTEST]-----------------------------------------------------------------------
[teststate_publishtest][failed]
SUMMARY
 * RESULT: FAIL
 * TESTS: 0
 * ERRORS: 0
 * FAILURES: 1
ERROR: The following tests failed to run:
 * teststate_publishtest
```

**Comment by hi-kondo** [comment]
Local test `rostest seed_r7_samples demo.tests` succeeded, but CI failed.
```
[ INFO] [1575290702.098269966]: max: 23.193792 [ms], ave: 20.173325 [ms]
[ INFO] [1575290702.574604240]: Planning request received for MoveGroup action. Forwarding to planning pipeline.
[ INFO] [1575290702.584485196]: Planner configuration 'torso' will use planner 'geometric::RRTConnect'. Additional configuration parameters will be set when the planner is constructed.
[ INFO] [1575290702.586614535]: RRTConnect: Starting planning with 1 states already in datastructure
[ INFO] [1575290702.731180081]: RRTConnect: Created 5 states (2 start + 3 goal)
[ INFO] [1575290702.731442091]: Solution found in 0.146058 seconds
[ INFO] [1575290702.968390439]: SimpleSetup: Path simplification took 0.214821 seconds and changed from 4 to 2 states
[ INFO] [1575290703.007820629]: Execution request received
[Testcase: teststate_publishtest] ... ok
[ROSTEST]-----------------------------------------------------------------------
[seed_r7_samples.rosunit-state_publishtest/test_publish][FAILURE]---------------
Topic [/server_name/smach/container_status] is not published
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/opt/ros/kinetic/share/rostest/nodes/publishtest", line 149, in test_publish
    'Topic [%s] is not published' % (checker.topic_name))
  File "/usr/lib/python2.7/unittest/case.py", line 422, in assertTrue
    raise self.failureException(msg)
--------------------------------------------------------------------------------
SUMMARY
 * RESULT: FAIL
 * TESTS: 1
 * ERRORS: 0
 * FAILURES: 1
```

**Comment by hi-kondo** [comment]
#61 is fixing #57 error and test at local.

**Comment by hi-kondo** [comment]
Topic timeout in demo.text changed to 30, the problem is resolved amd ci test passed.

**Comment by hi-kondo** [comment]
#61 merged
